### ISSUE TITLE
ENH: Introduce a fileformat for describing pipeline and model

### ISSUE THREAD

**Issue by andersbogsnes** [andersbogsnes/ml_tooling#166]
If we could describe the pipeline using a yaml style syntax, we could set up experiments by changing config files, both documenting results for each configuration of model, but also have the ability to serialize a given model into a string representation.

```yaml
features:
  age:
    - Select
        colname: "Age"
    - StandardScaler
        mean: 2.5
        std: 0.6
    - FillNA
       fillvalue: 0
model:
  RandomForestClassifier:
    num_estimators: 100
    max_depth: 10
```
